org: testingswa
service: elevenlabs-postcall-webhook

provider:
  name: aws
  runtime: python3.12
  region: ap-south-1
  stage: ${opt:stage, "dev"}
  timeout: 30
  memorySize: 256
  environment:
    SUPABASE_URL: ${ssm:/kovon/nurse/${self:provider.stage}/SUPABASE_URL}
    SUPABASE_KEY: ${ssm:/kovon/nurse/${self:provider.stage}/SUPABASE_KEY}
    BUCKET_NAME: ${ssm:/kovon/nurse/${self:provider.stage}/BUCKET_NAME}
    CALLEE_NUMBER: ${ssm:/kovon/nurse/${self:provider.stage}/CALLEE_NUMBER}
    GOOGLE_API_KEY: ${ssm:/kovon/${self:provider.stage}/nurse/GOOGLE_API_KEY}
    GEMINI_MODEL: "gemini-2.5-flash"
    SUPABASE_TABLE: "voice_calls"

plugins:
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true

functions:
  webhook:
    handler: app.lambda_handler
    events:
      - httpApi:
          path: /webhook
          method: post

package:
  patterns:
    - python/**
    - "!venv/**"
    - "!__pycache__/**"
    - "!.git/**"
    - "!.env*"
